const dbextension = [
  "The Quintessential Quintuplets Movie",
  "The Quintessential Quintuplets",
  "The Quintessential Quintuplets 2",
  "PR Card 【Weiẞ Side】",
  "Attack on Titan",
  "Attack On Titan: Final Season",
  "Attack on Titan Vol.2",
  "Fate/Apocrypha",
  "Arifureta: From Commonplace to World’s Strongest",
  "Adventure Time",
  "Avatar: The Last Airbender",
  "Accel・World",
  "Accel・World -Infinite Burst-",
  "Azur Lane",
  "BanG Dream!",
  "BanG Dream! Girls Band Party! 5th Anniversary",
  "BanG Dream! Girls Band Party Morfonica×RAISE A SUILEN",
  "BanG Dream! Girls Band Party Extra Booster Poppin’Party×Roselia",
  "BanG Dream! Vol.2",
  "BanG Dream! Girls Band Party!",
  "BanG Dream! Girls Band Party! Vol.2",
  "BanG Dream! Girls Band Party! MULTI LIVE",
  "BOFURI: I Don’t Want to Get Hurt, so I’ll Max Out My Defense.",
  "BAKEMONOGATARI",
  "Batman Ninja",
  "Cardcaptor Sakura : Clear Card",
  "Chainsaw Man",
  "Date A Live",
  "Date A Live Vol.2",
  "Date A Bullet",
  "Is It Wrong to Try to Pick Up Girls in a Dungeon?",
  "Disgaea",
  "Fate/Grand Order Absolute Demonic Front: Babylonia",
  "Fate/Grand Order THE MOVIE Divine Realm of the Round Table: Camelot",
  "Fujimi Fantasia Bunko",
  "Fate/stay night [Heaven’s Feel]",
  "Fate/stay night [Heaven's Feel] Vol.2",
  "Fate/stay night [Unlimited Blade Works]",
  "Fate/stay night [Unlimited Blade Works] Vol.2",
  "FAIRY TAIL ver.E",
  "Fate/Zero",
  "PR Card 【Schwarz Side】",
  "SAO Alternative – Gun Gale Online –",
  "Guilty Gear -Strive-",
  "GURREN LAGANN",
  "The Fruit of Grisaia",
  "hololive production Vol.2",
  "hololive production",
  "hololive production",
  "THE IDOLM@STER CINDERELLA GIRLS",
  "JoJo's Bizarre Adventure: Golden Wind",
  "Kancolle",
  "Kancolle, 2nd Fleet",
  "KanColle : Arrival! Reinforcement Fleets from Europe!",
  "KanColle : Fleet in the Deep Sea, Sighted!",
  "Kaguya-sama: Love is War",
  "Kaguya-sama: Love Is War?",
  "KILL la KILL",
  "Power Up Set 2023 - KILL La KILL",
  "Miss Kobayashi’s Dragon Maid",
  "Rent-A-Girlfriend",
  "KONOSUBA -God’s blessing on this wonderful world!",
  "KONOSUBA -God’s blessing on this wonderful world! Legend of Crimson",
  "KONOSUBA -God’s blessing on this wonderful world! 2",
  "LOG HORIZON",
  "Power Up Set 2023 - LOG HORIZON",
  "Love Live!",
  "Love Live! Vol.2",
  "Love Live! DX",
  "Love Live! DX Vol.2",
  "Love Live! Sunshine!!",
  "Love Live! Sunshine!!",
  "【Tutorial Deck】 Detective Opera Milky Holmes",
  "Puella Magi Madoka Magica",
  "PUELLA MAGI MADOKA MAGICA THE MOVIE -Rebellion-",
  "Mob Psycho 100",
  "Magia Record: Puella Magi Madoka Magica Side Story",
  'TV Anime "Magia Record: Puella Magi Madoka Magica Side Story"',
  "Mushoku Tensei: Jobless Reincarnation",
  "No Game No Life",
  "NISEKOI -False Love- ver.E",
  "NISEKOI: -False Love-",
  "NISEMONOGATARI",
  "Nazarick: Tomb of the Undead",
  "Nazarick: Tomb of the Undead Vol.2",
  "Persona 4 ver.E",
  "Persona 5",
  "Hatsune Miku -Project DIVA- ƒ",
  "Hatsune Miku: Project DIVA F 2nd",
  "Fate/kaleid liner PRISMA ILLYA",
  "Revue Starlight",
  "Revue Starlight -Re LIVE-",
  "Revue Starlight The Movie",
  "RWBY",
  "Re:ZERO -Starting Life in Another World-",
  "Re:ZERO -Starting Life in Another World- Memory Snow",
  "Re:ZERO -Starting Life in Another World- The Frozen Bond",
  "Re:ZERO -Starting Life in Another World- Vol.2",
  "Animation Sword Art Online 10th Anniversary",
  "Sword Art Online -Alicization-",
  "Sword Art Online -Alicization- Vol.2",
  "Sword Art Online",
  "Sword Art Online Vol.2",
  "Sword Art Online II",
  "Sword Art Online Ⅱ Vol.2",
  "Sword Art Online The Movie – Ordinal Scale –",
  "Sword Art Online Re: Edit",
  "Rascal Does Not Dream of Bunny Girl Senpai",
  "Rascal Does Not Dream of a Dreaming Girl",
  "The Seven Deadly Sins",
  "The Seven Deadly Sins: Revival of The Commandments",
  "Saekano: How to Raise a Boring Girlfriend",
  "Saekano♭ How to Raise a Boring Girlfriend. flat",
  "SPY x FAMILY",
  "The Melancholy of Haruhi Suzumiya",
  "Power Up Set 2023 - The Melancholy of Suzumiya Haruhi",
  "The Melancholy of Haruhi Suzumiya",
  "To Loveru Darkness 2nd",
  "Tokyo Revengers",
  "That Time I Got Reincarnated as a Slime Vol.3",
  "That Time I Got Reincarnated as a Slime",
  "That Time I Got Reincarnated as a Slime Vol.2"
]
export default dbextension
