export const jpFileNames = [
  "5HY_W101.json",
  "5HY_W83.json",
  "5HY_W90.json",
  "5HY_WE43.json",
  "AB_W11.json",
  "AB_W31.json",
  "AB_WE10.json",
  "AB_WE14.json",
  "AGS_W108.json",
  "ALL_S76.json",
  "ALL_S90.json",
  "AOT_S35.json",
  "AOT_S50.json",
  "APO_S53.json",
  "ARI_S103.json",
  "AW_S18.json",
  "AW_S43.json",
  "AYT_W110.json",
  "AZL_S102.json",
  "BAV_W112.json",
  "BD_W47.json",
  "BD_W54.json",
  "BD_W63.json",
  "BD_W73.json",
  "BD_W95.json",
  "BD_WE31.json",
  "BD_WE32.json",
  "BD_WE34.json",
  "BD_WE35.json",
  "BFR_S78.json",
  "BM_S15.json",
  "BR_SE06.json",
  "BTR_W107.json",
  "CC_S48.json",
  "CCS_W113.json",
  "CCS_W66.json",
  "CGS_WS01.json",
  "CHA_W40.json",
  "CL_WE01.json",
  "CL_WE04.json",
  "CL_WE07.json",
  "CL_WP01.json",
  "CN_SE02.json",
  "CS_S28.json",
  "CSM_S96.json",
  "DAL_W79.json",
  "DAL_W99.json",
  "DAL_WE33.json",
  "DBG_W87.json",
  "DC_W01.json",
  "DC_W09.json",
  "DC_W23.json",
  "DC_W81.json",
  "DC_WE01.json",
  "DC_WE02.json",
  "DC_WE08.json",
  "DC&LB_WE30.json",
  "DC3_W18.json",
  "DC3_WE16.json",
  "DC3_WE20.json",
  "DCT_S86.json",
  "DD_WE12.json",
  "DD_WE17.json",
  "DD_WE23.json",
  "DDM_S88.json",
  "DG_S02.json",
  "DG_SE08.json",
  "DG_SE17.json",
  "DJ_S97.json",
  "DPX_S104.json",
  "DS.json",
  "DS2_SE16.json",
  "EV_S12.json",
  "F_W65.json",
  "FGO_S75.json",
  "FGO_S87.json",
  "FH_SE03.json",
  "FS_S03.json",
  "FS_S34.json",
  "FS_S36.json",
  "FS_S64.json",
  "FS_S77.json",
  "FT_S09.json",
  "FT_SE10.json",
  "FXX_S57.json",
  "FZ_S17.json",
  "FZ_SE13.json",
  "G_WS02.json",
  "GBS_S63.json",
  "GC_S16.json",
  "GF_W33.json",
  "GF_W38.json",
  "GG_S23.json",
  "GGO_S59.json",
  "GL_S52.json",
  "GRI_S72.json",
  "GRI_S84.json",
  "GST_SE22.json",
  "GT_W29.json",
  "GU_W44.json",
  "GU_W57.json",
  "GU_W88.json",
  "GU_W94.json",
  "GU_WE26.json",
  "GZL_SE33.json",
  "HBR_W103.json",
  "HLL_WE28.json",
  "HLL_WE29.json",
  "HOL_W104.json",
  "HOL_W91.json",
  "HOL_WE36.json",
  "HOL_WE44.json",
  "HOL_WE45.json",
  "IM_S07.json",
  "IM_S14.json",
  "IM_S21.json",
  "IM_S30.json",
  "IM_SE04.json",
  "IM_SP01.json",
  "IMC_W41.json",
  "IMC_W43.json",
  "IMS_S93.json",
  "IMS&IAS_S61.json",
  "ISC_S81.json",
  "JJ_S66.json",
  "JJ_SE41.json",
  "JJ_SE42.json",
  "K_W78.json",
  "KC_S25.json",
  "KC_S31.json",
  "KC_S42.json",
  "KC_S67.json",
  "KC_SE28.json",
  "KEY_W102.json",
  "KF_S05.json",
  "KF_SE43.json",
  "KG_SE07.json",
  "KGL_S79.json",
  "KGL_S95.json",
  "KI_S44.json",
  "KLK_S27.json",
  "KLK_SP03.json",
  "KMD_W96.json",
  "KMN_W51.json",
  "KNK_W86.json",
  "KR_SE30.json",
  "KS_W49.json",
  "KS_W55.json",
  "KS_W75.json",
  "KS_W76.json",
  "LB_W02.json",
  "LB_W06.json",
  "LB_W21.json",
  "LB_WE02.json",
  "LB_WE18.json",
  "LB_WE21.json",
  "LH_SE20.json",
  "LH_SP02.json",
  "LL_W24.json",
  "LL_W28.json",
  "LL_W34.json",
  "LL_W36.json",
  "LL_W68.json",
  "LL_WE19.json",
  "LL_WE24.json",
  "LL_WE25.json",
  "LL_WE38.json",
  "LL_WE39.json",
  "LNJ_W85.json",
  "LNJ_W97.json",
  "LOD_S74.json",
  "LRC_W105.json",
  "LS_W05.json",
  "LSP_W92.json",
  "LSS_W45.json",
  "LSS_W53.json",
  "LSS_W69.json",
  "LSS_WE27.json",
  "MAR_S89.json",
  "MAR_SE40.json",
  "MB_S10.json",
  "MDE_SE45.json",
  "MF_S13.json",
  "MG_S39.json",
  "MH_WE03.json",
  "MH_WE05.json",
  "MK_S11.json",
  "MK_S33.json",
  "MK_SE09.json",
  "MK_SE11.json",
  "MK_SE29.json",
  "MK_SE34.json",
  "MK_SJ01.json",
  "MK2_S19.json",
  "MM_W17.json",
  "MM_W35.json",
  "MR_W59.json",
  "MR_W80.json",
  "MTI_S83.json",
  "N1_WE06.json",
  "N2_W25.json",
  "N2_W32.json",
  "NA_W12.json",
  "ND_W67.json",
  "NGL_S58.json",
  "NJ_WE11.json",
  "NK_W30.json",
  "NK_WE22.json",
  "NM_S24.json",
  "NR_W58.json",
  "NS_W04.json",
  "OMS_S41.json",
  "OSK_S107.json",
  "OVL_S62.json",
  "OVL_S99.json",
  "P3_S01.json",
  "P4_S08.json",
  "P4_SE01.json",
  "P4_SE12.json",
  "P4_SE15.json",
  "P5_S45.json",
  "PAD_S105.json",
  "PD_S22.json",
  "PD_S29.json",
  "PD_SE32.json",
  "PI_S40.json",
  "PI_SE18.json",
  "PI_SE24.json",
  "PI_SE31.json",
  "PI_SE36.json",
  "PJS_S109.json",
  "PJS_S91.json",
  "PP_SE14.json",
  "PQ_SE21.json",
  "PRD_W100.json",
  "PRD_W84.json",
  "PRI_SE36.json",
  "PT_W07.json",
  "PXR_S94.json",
  "PY_S38.json",
  "RG_W10.json",
  "RG_W13.json",
  "RG_W26.json",
  "RG_WP03.json",
  "RN_W16.json",
  "RSK_SE44.json",
  "RSL_S56.json",
  "RSL_S69.json",
  "RSL_S98.json",
  "RSL_SE38.json",
  "RW_W15.json",
  "RW_W20.json",
  "RW_W48.json",
  "RZ_S46.json",
  "RZ_S55.json",
  "RZ_S68.json",
  "RZ_SE35.json",
  "S_W62.json",
  "SAO_S100.json",
  "SAO_S20.json",
  "SAO_S26.json",
  "SAO_S47.json",
  "SAO_S51.json",
  "SAO_S65.json",
  "SAO_S71.json",
  "SAO_S80.json",
  "SAO_SE23.json",
  "SAO_SE26.json",
  "SB_S06.json",
  "SB_SE05.json",
  "SBY_W114.json",
  "SBY_W64.json",
  "SBY_W77.json",
  "SE_S04.json",
  "SFN_S108.json",
  "SG_W19.json",
  "SG_W27.json",
  "SG_W39.json",
  "SG_W52.json",
  "SG_W70.json",
  "SG_W72.json",
  "SG_W89.json",
  "SGS_S37.json",
  "SHS_W56.json",
  "SHS_W71.json",
  "SHS_W98.json",
  "SIx_W109.json",
  "SKR_S73.json",
  "SMP_W60.json",
  "SMP_W82.json",
  "SPY_S106.json",
  "SR_SE25.json",
  "SS_W14.json",
  "SS_WE15.json",
  "SS_WE41.json",
  "STG_S60.json",
  "SW_S49.json",
  "SW_SE39.json",
  "SY_W08.json",
  "SY_WE09.json",
  "SY_WP02.json",
  "TF_S32.json",
  "TL_W37.json",
  "TL_W42.json",
  "TRV_S92.json",
  "TSK_S101.json",
  "TSK_S70.json",
  "TSK_S82.json",
  "UMA_W106.json",
  "VR_W22.json",
  "VS_W50.json",
  "Woo_SE19.json",
  "WS_WPR.json",
  "WTR_S85.json",
  "YHN_W111.json",
  "YYS_W61.json",
  "ZLS_W93.json",
  "ZM_WE13.json",
  "ZM_W03.json"
]

export const jpExtension = [
  "The Quintessential Quintuplets Movie",
  "The Quintessential Quintuplets",
  "The Quintessential Quintuplets 2",
  "Quintuplets Premium Booster",
  "Angel Beats! & Kud Wafter",
  "PR Card 【Weiẞ Side】",
  "Angel Beats! EP",
  "Angel Beats! EB Vol.02",
  "Alice Gear Aegis",
  "Assualt Lily",
  "Assault Lily vol. 2",
  "Attack on Titan",
  "Shingeki no Kyoujin Vol.2",
  "Fate/Apocrypha",
  "Arifureta: From Commonplace to World’s Strongest",
  "Accel・World",
  "Accel World -Infinite Burst-",
  "Ayakashi Triangle",
  "Azur Lane",
  "Blue Archive",
  "BanG Dream!",
  "BanG Dream! Girls Band Party",
  "BanG Dream! Girls Band Party",
  "BanG Dream! Vol.2",
  "BanG Dream! Girls Band Party! 5th Anniversary",
  "BanG Dream Special Pack",
  "BanG Dream Premium Booster",
  "BanG Dream! Girls Band Party Morfonica×RAISE A SUILEN",
  "BanG Dream! Girls Band Party Extra Booster Poppin’Party×Roselia",
  "BOFURI: I Don’t Want to Get Hurt, so I’ll Max Out My Defense.",
  "BAKEMONOGATARI",
  "Black Rock Shooter EP",
  "Bocchi The Rock",
  "Chain Chronicle: The Light of Haecceitas",
  "Cardcaptor Sakura 25th Anniversary",
  "Cardcaptor Sakura Clear Card Arc",
  "Card Game Shiyoko",
  "Charlotte",
  "Clannad Vol.1",
  "Clannad Vol.2 After Story",
  "Clannad Vol.3",
  "Clannad (Power-Up Set)",
  "CANAAN",
  "Crayon Shin-chan",
  "Chainsaw Man",
  "Date A Live",
  "Date A Live Vol.2",
  "Date A Bullet",
  "Kami-sama ni Natta Hi",
  "D.C. D.C.II",
  "D.C. D.C.II Plus Communication",
  "D.C. Da Capo 10th Anniversary Mix",
  "CIRCUS 20th Anniversary",
  "D.C. D.C.II EP",
  "D.C.II P.C. EP",
  "D.C. D.C.II Plus Communication EP",
  "Da Capo VS Little Busters",
  "D.C. D.C.III",
  "Anime D.C. Da Capo III",
  "D.C. Da Capo Sakurasaku Pack EB",
  "D_CIDE TRAUMEREI",
  "Dog Days",
  "Dog Days'",
  'Dog Days"',
  "Is It Wrong to Try to Pick Up Girls in a Dungeon?",
  "Disgaea",
  "Disgaea 4 EP",
  "Disgaea D2",
  "D4DJ",
  "Disney 100",
  "D.S. -Dal Segno- & D.C.III With You",
  "Devil Survivor 2",
  "Rebuild of Evangelion",
  "Fujimi Fantasia Bunko",
  "Fate/Grand Order Absolute Demonic Front: Babylonia",
  "Fate/Grand Order THE MOVIE Divine Realm of the Round Table: Camelot",
  "Fate/hollow ataraxia",
  "Fate/stay night",
  "Fate/stay night [Unlimited Blade Works]",
  "Fate/stay night [Unlimited Blade Works] Vol.2",
  "Fate/stay night [Heaven’s Feel]",
  "Fate/stay night [Heaven's Feel] Vol.2",
  "Fairy Tail",
  "Fairy Tail EP",
  "Darlin' in the Franxx",
  "Fate/Zero",
  "Fate/Zero EP",
  "Dengeki Bunko",
  "PR Card 【Schwarz Side】",
  "Guilty Crown",
  "Girlfriend (Beta)",
  "Girlfriend (Beta) Vol.2",
  "Suisei no Gargantia",
  "SAO Alternative – Gun Gale Online –",
  "GURREN LAGANN",
  "The Fruit of Grisaia",
  "Grisaia no Kajitsu Vol.2",
  "Choubakuretsu Ijigen Menko Battle: Gigant Shooter",
  "Genei wo Kakeru Taiyou",
  "Gochuumon wa Usagi Desu ka??",
  "Gochuumon wa Usagi Desu ka?? Dear My Sister",
  "Gochuumon wa Usagi Desu ka? BLOOM",
  "Gochiusa Re:Edit",
  "Gochuumon wa Usagi Desu ka?? EB",
  "Godzilla The Animation",
  "Heaven Burns Red",
  "Hina Logic from Luck & Logic",
  "Hina Logic from Luck & Logic Vol.2",
  "hololive production Vol.2",
  "hololive production",
  "hololive production",
  "Hololive Premium Booster Summer Collection",
  "Hololive Ambassadors Premium Booster",
  "THE iDOLM@STER",
  "THE IDOLM@STER2",
  "THE iDOLM@STER (Anime)",
  "THE iDOLM@STER (Movie)",
  "THE iDOLM@STER Dearly Stars",
  "THE iDOLM@STER (Power-Up Set)",
  "THE IDOLM@STER CINDERELLA GIRLS",
  "The iDOLM@STER Cinderella Girls 2nd Season",
  "Million Live Vol.2",
  "The Idolmaster Million Live!",
  "The iDOLM@STER Shiny Colors Booster Box",
  "JoJo's Bizarre Adventure: Golden Wind",
  "Jojo Stardust Crusaders",
  "Jojo Stone Ocean",
  "Key 20th Anniversary",
  "Kancolle",
  "Kantai Collection - Kancolle 2nd Fleet",
  "Kantai Collection - KanColle Arrival of the European Fleet",
  "Kantai Collection - Kancolle 5th Phase",
  "Kantai Collection - KanColle Abyssal Fleet Edition",
  "Key All Star",
  "The King of Fighters",
  "King of Fighters Premium Booster",
  "Katanagatari",
  "Kaguya-sama: Love is War",
  "Kaguya-sama: Love Is War?",
  "Kiznaiver",
  "KILL la KILL",
  "Power Up Set 2023 - KILL La KILL",
  "Miss Kobayashi’s Dragon Maid",
  "Kemono Friends",
  "Rent-A-Girlfriend",
  "Kyoukai no Rinne",
  "KONOSUBA -God’s blessing on this wonderful world!",
  "Kono Subarashii Sekai ni Shukufuku wo! 2",
  "Various",
  "KONOSUBA -God’s blessing on this wonderful world! Legend of Crimson",
  "Little Busters!",
  "Little Busters! Ecstacy",
  "Little Busters! (Anime)",
  "Little Busters! Ecstacy EP",
  "Anime Little Busters! - Refrain",
  "Little Busters! Card Mission EB",
  "LOG HORIZON",
  "Power Up Set 2023 - LOG HORIZON",
  "Love Live!",
  "Love Live! feat. School Idol Festival",
  "Love Live! Vol.2",
  "Love Live! School Idol Festival Vol.2",
  "Love Live School Idol Festival Vol.3 ~6th Anniversary~",
  "Love Live! EB",
  "Love Live! The School Idol Movie Extra Booster",
  "Love Live! feat. School Idol Festival Variety Set",
  "Love Live Thanksgiving Festival",
  "Love Live! Sukufesu 10th Anniversary",
  "Love Live! Nijigasaki Academy School Idol Club",
  "Love Live Nijigasaki Anime",
  "Lost Decade",
  "Lycoris Recoil",
  "Lucky Star",
  "Love Live! Superstar!!",
  "Love Live! Sunshine!!",
  "Love Live! Sunshine!! Vol.2",
  "Love Live Sunshine!! School Idol Festival ~6th Anniversary~",
  "Love Live! Sunshine! Extra Booster",
  "Marvel",
  "Marvel Premium Booster",
  "Melty Blood",
  "Macross Delta Premium Booster",
  "Macross Frontier",
  "Monogatari Series Second Season",
  "Sora wo Kakeru Shoujo/Mai-Hime & Mai-Otome",
  "Sora wo Kakeru Shoujo/Mai-Hime & Mai-Otome Vol.2",
  "【Tutorial Deck】 Detective Opera Milky Holmes",
  "Milky Holmes Second Stage Edition",
  "Milky Holmes - Phantom Thieves Empire Strikes Back",
  "Milky Holmes - Counterattack of Genius4",
  "Milky Holmes the Movie -Milky Holmes Counterattack-",
  "Milky Holmes Concert Promos",
  "Milky Holmes Party Pack",
  "Detective Opera Milky Holmes 2",
  "Puella Magi Madoka Magica",
  "Puella Magi Madoka Magica the Movie: Rebellion",
  "Magia Record: Puella Magi Madoka Magica Side Story",
  'TV Anime "Magia Record: Puella Magi Madoka Magica Side Story"',
  "Mushoku Tensei: Jobless Reincarnation",
  "Mahou Shoujo Lyrical Nanoha The MOVIE 1st",
  "Mahou Shoujo Lyrical Nanoha The MOVIE 2nd A's",
  "Mahou Shoujo Lyrical Nanoha THE MOVIE 1st & 2nd A's",
  "Mahou Shoujo Lyrical Nanoha A's",
  "Mahou Shoujo Lyrical Nanoha Detonation",
  "No Game No Life",
  "Nichijou",
  "NISEKOI -False Love- ver.E",
  "Nisekoi: EB",
  "NISEMONOGATARI",
  "Mahou Shoujo Lyrical Nanoha Reflection",
  "Mahou Shoujo Lyrical Nanoha StrikerS",
  "Osomatsu-san",
  "Oshi no Ko",
  "Nazarick: Tomb of the Undead",
  "Nazarick: Tomb of the Undead Vol.2",
  "Persona 3",
  "Persona 4",
  "Persona 4 EP",
  "Persona 4: The Animation",
  "Persona 4 The Ultimate",
  "Persona 5",
  "Puzzle And Dragon",
  "Hatsune Miku Project Diva f",
  "Hatsune Miku Project Diva f 2nd",
  "Hatsune Miku ~Project DIVA~ X HD",
  "Fate/kaleid liner Prisma ☆ Illya 2wei Herz",
  "Fate/kaleid liner Prisma ☆ Ilya",
  "Fate/kaleid liner Prisma ☆ Ilya Zwei!",
  "Fate/kaleid liner Prisma ☆ Illya 3rei!!",
  "Fate/kaleid liner Prisma ☆ Illya Prisma ☆ Phantasm",
  "Project Sekai Colorful Stage Vol 2",
  "Project Sekai",
  "Psycho-Pass",
  "Persona Q Shadow of the Labyrinth",
  "Princess Connect Vol.2",
  "Princess Connect! Re:Dive (Anime)",
  "Prisma Illya Phantasm",
  "Phantom ~Requiem for the Phantom~",
  "Pixar All Stars",
  "Puyo Puyo",
  "Index & Railgun",
  "Index II & Railgun",
  "To Aru Kagaku no Railgun S",
  "Railgun Power-Up",
  "Robotics;Notes",
  "Rear Sekai",
  "Revue Starlight",
  "Revue Starlight -Re LIVE-",
  "Revue Starlight The Movie",
  "Revue Starlight The Live Edel Delight Portrait Booster",
  "Rewrite",
  "Rewrite Harvest festa!",
  "Rewrite TV Anime",
  "Re:ZERO -Starting Life in Another World-",
  "Re:Zero kara Hajimeru Isekai Seikatsu Vol.2",
  "Re:ZERO -Starting Life in Another World- Memory Snow",
  "Re:ZERO -Starting Life in Another World- The Frozen Bond",
  "Kadokawa Sneaker Bunko",
  "Animation Sword Art Online 10th Anniversary",
  "Sword Art Online",
  "Sword Art Online Vol.2",
  "Sword Art Online Re:Edit",
  "Sword Art Online: Ordinal Scale",
  "Sword Art Online -Alicization-",
  "Sword Art Online 10th Anniversary",
  "Sword Art Online -Alicization- Vol.2",
  "Sword Art Online II EB",
  "Sword Art Online II Vol.2 EB",
  "Sengoku Basara",
  "Sengoku Basara EP",
  "Aobuta Movie Booster",
  "Rascal Does Not Dream of Bunny Girl Senpai",
  "Rascal Does Not Dream of a Dreaming Girl",
  "Shining Force EXA",
  "Sousou no Frieren",
  "Senki Zesshou Symphogear",
  "Senki Zesshou Symphogear G",
  "Senki Zesshou Symphogear GX",
  "Senki Zesshou Symphogear XD Unlimited",
  "Senki Zesshou Symphogear AXZ",
  "Senki Zesshou Symphogear XD UNLIMITED EXTEND",
  "Senki Zessho Symphogear XV",
  "Schoolgirl Strikers",
  "Saekano: How to Raise a Boring Girlfriend",
  "Saekano♭ How to Raise a Boring Girlfriend. flat",
  "Saekano Fine",
  "Love Live! SIF2 Miracle Live!",
  "Shin Sakura Taisen",
  "Summer Pockets",
  "Summer Pockets REFLECTION BLUE",
  "SPY x FAMILY",
  "Shining Resonance",
  "Shakugan no Shana",
  "Shakugan no Shana F EP",
  "Shana Premium Booster",
  "STEINS;GATE",
  "STAR WARS",
  "Star Wars Premium Booster",
  "The Melancholy of Haruhi Suzumiya",
  "Suzumiya Haruhi no Yuutsu EP",
  "Power Up Set 2023 - The Melancholy of Suzumiya Haruhi",
  "Terra Formars",
  "To Love Ru - Trouble - Darkness 2nd",
  "To Love Ru - Trouble - Darkness 2nd Vol.2",
  "Tokyo Revengers",
  "That Time I Got Reincarnated as a Slime Vol.3",
  "That Time I Got Reincarnated as a Slime",
  "That Time I Got Reincarnated as a Slime Vol.2",
  "Uma Musume",
  "Vividred Operation",
  "Vivid Strike!!",
  "Wooser's Hand-to-Mouth Life",
  "Weiss Schwarz Promos",
  "World Trigger",
  "Genjitsu no Yohane",
  "Yuragi-sou no Yuuna-san",
  "Zombie Land Saga Revenge",
  "Zero no Tsukaima F",
  "Zero no Tsukaima"
]
